### ISSUE TITLE
error with Destructuring assignment

### ISSUE THREAD

**Issue by joost2076** [fizker/minifier#19]
Hi, 
I tried incorporating destructuring assignments in my code, but since then the minifier failes.
Simply trying to minifiy 
`var [a,b] = [1, 2]; `
leads to the error below. 
Works fine without these type of statements on my computer. 
Is this an error, simply not supported, or am I making a mistake ?
Thanks,
Joost

undefined:1534
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at as_symbol (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2664:27)
    at vardefs (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2432:25)
    at var_ (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2446:27)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2194:30)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2073:24)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2827:23)
    at Object.parse (eval at <anonymous> (/usr/local/lib/node_modules/minifier/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2837:7)

**Comment by fizker** [comment]
It is not supported by the version of uglify used here. [It is also not supported by IE and Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/destructuringes6), so you want to [run it through Babel](http://babeljs.io) anyway. If you do that first, then there should be no problems.

Babel would also allow you to use all other kinds of ES2015+ goodies, so I highly recommend it.

**Comment by joost2076** [comment]
thanks for the quick response!

**Comment by fizker** [comment]
Just for reference, this would be dependent on https://github.com/mishoo/UglifyJS2/issues/448 to avoid running Babel first
