### ISSUE TITLE
seems to be broken on node-v0.12.4-darwin-x64

### ISSUE THREAD

**Issue by frumbert** [fizker/minifier#24]
I have nodejs version node-v0.12.4-darwin-x64
I have npm version 3.10.9

I get

/usr/local/node-v0.12.4-darwin-x64/lib/node_modules/minifier/src/minify.js:67
		files.every(x => handleInputs([x]))
		              ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/node-v0.12.4-darwin-x64/lib/node_modules/minifier/index.js:4:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by fizker** [comment]
That's expected, and the reason for this: https://github.com/fizker/minifier/blob/master/package.json#L37.

You might have some luck running it via babel
