### ISSUE TITLE
Minifier does not work on a

### ISSUE THREAD

**Issue by XeroCodeIT** [fizker/minifier#25]
I set up minify by 'npm install -g minifier'
It is located here:
C:\Users\User\AppData\Roaming\npm\node_modules\minifier

Trying to minify a css file results in an error message.

I'm using Windows 10 , my NPM was set up as part of Visual Studio, I expect that might be part of the problem.
I might just switch to a Ubuntu VM for running node scripts.

But I'm a complete beginner with node, perhaps there is something that I needed to do but did not?

```
F:\projects\test>minify style2.css;
C:\Users\User\AppData\Roaming\npm\node_modules\minifier\src\minify.js:67
                files.every(x => handleInputs([x]))
                              ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Ingus\AppData\Roaming\npm\node_modules\minifier\index.js:4:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by fizker** [comment]
You are using an old version of node that does not support arrow functions. Support for arrow functions was introduced in node 4. I do not intend to support old node versions, so you have to either update your node install or run through babel or a similar transpiler.
